git:
    depth: 1

sudo: false

language: node_js

cache:
    directories:
        - node_modules

node_js:
    - "5"

branches:
    only:
        - master
before_script:
    - ". ./jscs.sh"
script:
    - "npm run travis"
